### ISSUE TITLE
Suggestion: Add IMDB id to response

### ISSUE THREAD

**Issue by iZNunev** [AugustoMarcelo/mcuapi#10]
Hi,

I love the API and it does have sufficient stuff however, I would also like to build a personal app that has a bit more details, such as actors, additional images etc. Instead of adding those to the API it would be nice to have `imdb_id` for the movie/show returned so that we could make extra requests to movie databases to get extra info from there. 

What do you think?

**Comment by AugustoMarcelo** [comment]
Hi, @iZNunev 

Thanks for the feedback. I'm currently working to add some extra data like movies/tv shows related and characters. But your idea is interesting, I could add a column for external data. Could you give me an example value for the `imdb_id`?

**Comment by iZNunev** [comment]
Sure thing @AugustoMarcelo  :) When you search a movie in the IMDB the ID appears as part of the URL:
e.g 
Black widow: https://www.imdb.com/title/tt3480822/
the `imdb_id` in this case is `tt3480822`

**Comment by AugustoMarcelo** [comment]
Hi, @iZNunev 

Sorry for the delay to return. But I have implemented your suggestion. Now, Movies and TV Shows have an imdb_id property!
