### ISSUE TITLE
TV Shows Chronology

### ISSUE THREAD

**Issue by Zizico2** [AugustoMarcelo/mcuapi#12]
Any chance you include the TV Shows into the chronological order?

**Comment by AugustoMarcelo** [comment]
Hi, @Zizico2 

Thanks for the feedback! Do you say in relation to the TV Shows themselves or in relation to MCU in general?

**Comment by Zizico2** [comment]
I say in relation to the MCU in general. Maybe a new field? Not to break applications using the current Chronology (the relative order would remain the same, but it could mess up people using the actual numbers)

**Comment by Zizico2** [comment]
You could even add announced but not released titles to both movies and series and put "-1" in Chronology.

**Comment by AugustoMarcelo** [comment]
> I say in relation to the MCU in general. Maybe a new field? Not to break applications using the current Chronology (the relative order would remain the same, but it could mess up people using the actual numbers)

That's a little tricky question. I might need to use decimal numbers for TV series that are between one movie and another. For example, a TV series that is chronologically between the 14th order movie and the 15th order movie would receive the value 14.1. Also, they are different models and have different routes.

**Comment by AugustoMarcelo** [comment]
> You could even add announced but not released titles to both movies and series and put "-1" in Chronology.

This would affect the return of chronological order. That would put these movies and TV series ahead of the ones that have already been released.

**Comment by Zizico2** [comment]
It would be a "magic number". If it is documented that "-1" means "we don't know when it is set", it is up to the client using the API to take that into consideration.
