### ISSUE TITLE
Suggestion: replace autonumber id with uuid

### ISSUE THREAD

**Issue by deBasMan21** [AugustoMarcelo/mcuapi#18]
It would help me if the ids of the movies and shows are an UUID because in my project i want to give users options to save a project and therefore the id of any project needs to be unique. I can add my own UUID but it will change everytime a new api call is executed. If it is not too much trouble of course :).

**Comment by AugustoMarcelo** [comment]
Hi, @deBasMan21 

Thanks for the feedback. Now, this is not possible to be done since I do all the relationships between movies based on this incremental ID. Not sure if I did understand your problem very well, but despite I'm using an incremental ID, it is unique.

**Comment by deBasMan21** [comment]
Okay i will find my own solution then.
