### ISSUE TITLE
Api Application Error in Heroku since Sept 1

### ISSUE THREAD

**Issue by thanhtutzaw** [AugustoMarcelo/mcuapi#21]

**Comment by mikesz88** [comment]
My website broke because of this. Please resolve

**Comment by AugustoMarcelo** [comment]
Hi, guys

Not sure if you did notice, but this project uses Heroku free resources. The API was running until two days ago (27/09) when my free dynos ran out. I did a little increment and now is up again. But I suggest to you implement some fallback cache in your application.

FYI, these free resources will no longer be available on November 28th. I'll need to find a new host for my API.

**Comment by AugustoMarcelo** [comment]
> My website broke because of this. Please resolve

Giving a project star could be a good start before asking for something, huh? What do you think?

**Comment by mikesz88** [comment]
@AugustoMarcelo use cyclic.sh

That is where I changed my stuff too. Just as easy has heroku, if not easier.
