### ISSUE TITLE
Suggestion: Add the newest projects

### ISSUE THREAD

**Issue by BasBuijsen** [AugustoMarcelo/mcuapi#22]
I would like to see the newest projects in the api. The projects i am missing now are:
- Deadpool 3
- Werewolf by night
If you would like more information i could provide it for you.

**Comment by AugustoMarcelo** [comment]
@BasBuijsen thanks for the feedback. I have updated the database with Werewolf by night and other data. For while, I won't add Deadpool because I don't how it will be inserted into this universe. I think it's better we wait for more information about this.

**Comment by AugustoMarcelo** [comment]
I'll close the issue, but feel free to re-open it and talk about anything.
