### ISSUE TITLE
Covers link not working

### ISSUE THREAD

**Issue by aryan-suman333** [AugustoMarcelo/mcuapi#24]
Old covers link with raw.githubusercontent.com are not working.

**Comment by AugustoMarcelo** [comment]
Hi, @aryan-suman333. What error did you get? I did perform some tests and it seems to work correctly.

**Comment by aryan-suman333** [comment]
![Screenshot 2022-12-17 135017](https://user-images.githubusercontent.com/91591807/208232898-3f81e222-d623-4b07-a074-5509108c053c.png)
![Screenshot 2022-12-17 135130](https://user-images.githubusercontent.com/91591807/208232917-02ae37e6-90ca-4add-bfd6-3a0ba0f48f30.png)
cloudinary links are working but raw.githubusercontent links are not responding.

**Comment by AugustoMarcelo** [comment]
@aryan-suman333 the links are working for me. But I'll start to migrate the links to Cloudinary. As soon as I finished, I'll inform here

**Comment by AugustoMarcelo** [comment]
@aryan-suman333 I have updated all old links. Can you check it?

**Comment by valdemirfilho** [comment]
@AugustoMarcelo cover_url for Doctor Strange in the Multiverse of Madness not found.
[https://res.cloudinary.com/augustomarcelo/image/upload/v1675212381/mcuapi/gallery/Movies/doctor_strange_in_the_multiverse_of_madness/posters/1.jpg](https://res.cloudinary.com/augustomarcelo/image/upload/v1675212381/mcuapi/gallery/Movies/doctor_strange_in_the_multiverse_of_madness/posters/1.jpg)

**Comment by AugustoMarcelo** [comment]
@valdemirfilho It's fixed now!
