### ISSUE TITLE
Links caidos

### ISSUE THREAD

**Issue by frankcarmona14** [AugustoMarcelo/mcuapi#25]
Link de imagen de "Iron Man 2" y "doctor_strange_in_the_multiverse_of_madness" no muestran ninguna imagen.
![Captura de pantalla 2023-02-13 125257](https://user-images.githubusercontent.com/44358240/218450959-78fd8c50-d82d-4707-aeb9-94a7238ae5f5.png)

**Comment by AugustoMarcelo** [comment]
@frankcarmona14 Gracias por el aviso. Los arreglé
