### ISSUE TITLE
Broken cover links

### ISSUE THREAD

**Issue by alexCoding42** [AugustoMarcelo/mcuapi#29]
Hi,

Some links seem to be broken in the tv shows [endpoint](https://mcuapi.herokuapp.com/docs/#/TV%20Shows/get_api_v1_tvshows). I think it is related to the same issue https://github.com/AugustoMarcelo/mcuapi/issues/25
<img width="1216" alt="Capture d’écran 2023-02-24 à 23 24 06" src="https://user-images.githubusercontent.com/56698920/221306630-edf7605e-e3bb-441e-b131-413d19e5cb5d.png">
<img width="1219" alt="Capture d’écran 2023-02-24 à 23 24 35" src="https://user-images.githubusercontent.com/56698920/221306683-2fecf75c-d64d-4007-a19c-b27afd7e4082.png">

**Comment by AugustoMarcelo** [comment]
@alexCoding42 thanks for the feedback. I think I've messed up things... but now it's fixed!
