### ISSUE TITLE
Incorrect/Missing Related Movies

### ISSUE THREAD

**Issue by mpurcella** [AugustoMarcelo/mcuapi#30]
It seems like not all of the related movies are correct.  For example, the related movies for _Iron Man 2_ include _Iron Man 2_ but not _Iron Man:_
<img width="1440" alt="Screenshot 2023-03-02 at 4 41 37 PM" src="https://user-images.githubusercontent.com/75453046/222602889-72be405a-6b3c-43c2-a1ed-df5249d9282f.png">

Similarly, the related movies for _Iron Man 3_ include _Iron Man_ but not _Iron Man 2_. I haven't gone through all of the movies or shows, but wanted it to bring it to your attention.

**Comment by AugustoMarcelo** [comment]
@mpurcella thanks for pointing that out. I have adjusted them (or at least most of them). Let me know if you find anything else
