### ISSUE TITLE
API Error

### ISSUE THREAD

**Issue by Oshanotter** [AugustoMarcelo/mcuapi#33]
Any request to the api results in an application error. The response is: “An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command heroku logs --tail”

**Comment by AugustoMarcelo** [comment]
@Oshanotter issue solved. Can you check again?

**Comment by Oshanotter** [comment]
@AugustoMarcelo it works great! Thanks!
