### ISSUE TITLE
Error getting movies.

### ISSUE THREAD

**Issue by DanCanetti** [AugustoMarcelo/mcuapi#6]
Getting the following error in console log.

```
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
```

**Comment by AugustoMarcelo** [comment]
@DanCanetti It was something related to SSL. Here already normalized, try again. Thanks for the feedback!

**Comment by DanCanetti** [comment]
@AugustoMarcelo thanks! All working again now.

Thanks for the project 👍🏻

**Comment by DanCanetti** [comment]
@AugustoMarcelo thanks! All working again now.

Thanks for the project 👍🏻
