### ISSUE TITLE
Search endpoint

### ISSUE THREAD

**Issue by iZNunev** [AugustoMarcelo/mcuapi#9]
Hey, would it be possible to get a capability to search based on Phase and/or Saga? Or filter the results based on those?

**Comment by KristofKekesi** [comment]
Hi!

You can filter by adding the `?filter=saga=Infinity` ending. For the phase it is `?filter=phase=1`.

So the URLs should look like this:
```http
https://mcuapi.herokuapp.com/api/v1/movies?filter=phase=1
https://mcuapi.herokuapp.com/api/v1/movies?filter=saga=Infinity
```

You can view the Dev's words on this at #8.

**Comment by iZNunev** [comment]
Awesome! Thanks a lot :)
